plot(mlb11$runs ~ mlb11$at_bats, main = "Relationship between Runs and atBats", xlab = "At Bats", ylab = "Runs")
cor(mlb11$runs, mlb11$at_bats)
plot_ss(x = mlb11$at_bats, y = mlb11$runs)
plot_ss(x = mlb11$at_bats, y = mlb11$runs, showSquares = TRUE)
m1 <- lm(runs ~ at_bats, data = mlb11)
summary(m1)
plot_ss(x = mlb11$at_bats, y = mlb11$runs)
plot_ss(x = mlb11$at_bats, y = mlb11$runs)
plot_ss(x = mlb11$at_bats, y = mlb11$runs)
plot(mlb11$runs ~ mlb11$at_bats, main = "Relationship between Runs and Home runs", xlab = "Home Runs", ylab = "Runs")
cor(mlb11$runs, mlb11$homeruns)
m2 <- lm(runs ~ homeruns, data = mlb11)
summary(m2)
cor(mlb11$runs, mlb11$homeruns)
plot(mlb11$runs ~ mlb11$at_bats)
abline(m1)
plot(m1$residuals ~ mlb11$at_bats)
abline(h = 0, lty = 3) # adds a horizontal dashed line at y = 0
qqnorm(m1$residuals)
qqline(m1$residuals) # adds diagonal line to the normal prob plot
hist(m1$residuals)
